### ISSUE TITLE
Handle dragging duplicate courses in degree plans

### ISSUE THREAD

**Issue by aidigii** [acmutd/comet_planning#19]
## Problem
Upon the circumstance that course duplicates appear on the sidebar as a result of double majors, user might be confused by seeing these duplicates given they can only take one instance of a particular class. 

## Solution
Once user drags an instance of a duplicate on a semester board, the other duplicated instance disappears from the sidebar.

**Comment by WillieCubed** [comment]
Closing as duplicate of #6
