### ISSUE TITLE
Update existing UI to use Material-UI components

### ISSUE THREAD

**Issue by aishanids** [acmutd/comet_planning#21]
## Problem Description
The styling for all of the components are in the same file as the component.

## Proposed Problem Solution
Move all of the Material-UI styling into one file for cleaner code.

**Comment by WillieCubed** [comment]
I'm going to modify this issue a bit; as we talked in the last meeting, we'll do the following:
- Use Material-UI components whenever possible
  - Update `CourseCard` to be display as an actual Material-UI `Card`
  - Update the toolbar to be custom-styled `AppBar`

**Comment by WillieCubed** [comment]
Closed by #23
